{
  "swagger": "2.0",
  "info": {
    "title": "Easyac API",
    "description": "Navegue nos seus dados do Portal do Aluno SenacRS através de uma API Web. \n\nAs chamadas são feitas para a url https://api.easyac.xyz. Sendo, todas elas, trafegadas em HTTPS.\n\nEm nenhum momento as informações de login do aluno são persistidas em banco de dados. Para saber mais sobre o projeto acesse https://github.com/easyac/crawler.\n",
    "version": "1.0.0",
    "contact": {
      "name": "Ícaro Heimig",
      "email": "icaro.mh@gmail.com"
    }
  },
  "host": "api.easyac.xyz",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "in": "header",
      "name": "api_key"
    }
  },
  "produces": [
    "application/json"
  ],
  "paths": {
    "/user": {
      "post": {
        "summary": "Cadastrar usuário",
        "description": "Cadastra um usuário na API Easyac\n",
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "tags": [
          "Usuario"
        ],
        "responses": {
          "200": {
            "description": "Ok"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      },
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "summary": "Visualizar dados do usuário",
        "description": "Visualizar dados de um usuário na API Easyac\n",
        "tags": [
          "Usuario"
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/UserSchema"
            }
          },
          "400": {
            "description": "Bad Request"
          }
        }
      },
      "put": {
        "security": [
          {
            "api_key": []
          }
        ],
        "summary": "Atualizar usuário",
        "description": "Atualizar usuário autenticado na API Easyac\n",
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "tags": [
          "Usuario"
        ],
        "responses": {
          "200": {
            "description": "Ok"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/user/auth": {
      "post": {
        "summary": "Autenticar usuário",
        "description": "A partir de dados de acesso de um usuário, autentica-se na API e é retornado um JSON Web Token válido para autenticar futuras requisições\nPara utilizar o token gerado, insira ele no campo Token no topo da página e clique em \"Explorar\"\n",
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        ],
        "tags": [
          "Usuario"
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/AlunoToken"
            }
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/user/revalidate": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "summary": "Renovar token de acesso",
        "description": "Solicita a renovação do token de acesso\n",
        "tags": [
          "Usuario"
        ],
        "responses": {
          "200": {
            "description": "Ok"
          },
          "400": {
            "description": "Bad Request"
          }
        }
      }
    },
    "/senac/login": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "summary": "Autenticar aluno no Portal do Aluno SenacRS",
        "description": "A partir das credenciais de acesso de um aluno, autentica ele no Portal do Aluno SenacRS e permite o robô buscar os dados no Portal.\n",
        "parameters": [
          {
            "name": "aluno",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Aluno"
            }
          }
        ],
        "tags": [
          "Senac"
        ],
        "responses": {
          "200": {
            "description": "Ok"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/senac/associate": {
      "put": {
        "security": [
          {
            "api_key": []
          }
        ],
        "summary": "Associar credenciais do aluno ao usuário",
        "description": "Associa as credenciais de acesso de um aluno ao usuário logado na API Easyac.\n",
        "parameters": [
          {
            "name": "aluno",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Aluno"
            }
          }
        ],
        "tags": [
          "Senac"
        ],
        "responses": {
          "200": {
            "description": "Ok"
          },
          "400": {
            "description": "Bad Request"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/senac/sync": {
      "post": {
        "security": [
          {
            "api_key": []
          }
        ],
        "summary": "Solicitar sincronia dos dados do Portal do Aluno SenacRS",
        "description": "Solicita ao robô que busque e salve os dados do Portal do Aluno SenacRS na API Easyac\n",
        "tags": [
          "Senac"
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/senac/sync/status": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "summary": "Verificar status da última solicitação de sincronia",
        "description": "Retorna o status da última atualização.\n",
        "tags": [
          "Senac"
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "$ref": "#/definitions/Status"
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/classes": {
      "get": {
        "security": [
          {
            "api_key": []
          }
        ],
        "summary": "Listar disciplinas do aluno autenticado",
        "description": "Retorna a lista de disciplinas de acordo com os dados solicitados, contendo informações sobre notas e faltas.\n",
        "parameters": [
          {
            "name": "ano",
            "in": "query",
            "description": "Ano letivo",
            "required": false,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "semestre",
            "in": "query",
            "description": "Semestre letivo",
            "required": false,
            "type": "integer",
            "format": "int32",
            "enum": [
              1,
              2
            ]
          }
        ],
        "tags": [
          "Aluno"
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Class"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    }
  },
  "definitions": {
    "AlunoToken": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        }
      },
      "example": {
        "token": "eyJhcGciUiJIUfI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjYxMTQyMDM3OCIsImlkIjoiNTdmMDNmOTMwZDg3NjcwMDEzOWJiY2NmIiwiaWF0IjoxNDc3NzkzMTk4fQ.ewbwafBHXxo4sdgRAfVcitBAdzViD7E4f8xTvRZbk7p4"
      }
    },
    "Status": {
      "type": "object",
      "properties": {
        "status": {
          "type": "string"
        }
      },
      "example": {
        "status": "pending"
      }
    },
    "Aluno": {
      "type": "object",
      "properties": {
        "unity": {
          "type": "integer"
        },
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "storePassword": {
          "type": "boolean"
        }
      },
      "example": {
        "unity": 63,
        "username": "631420378",
        "password": "tuasenha",
        "storePassword": false
      }
    },
    "User": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "example": {
        "email": "icaro.mh@gmail.com",
        "password": "tuasenha"
      }
    },
    "UserSchema": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "webToken": {
          "type": "string"
        },
        "senacCredentials": {
          "type": "object",
          "properties": {
            "username": {
              "type": "string"
            },
            "unity": {
              "type": "integer"
            },
            "storePassword": {
              "type": "boolean"
            },
            "lastSync": {
              "type": "string",
              "format": "date"
            },
            "isSyncing": {
              "type": "boolean"
            }
          }
        }
      },
      "example": {
        "email": "icaro.mh@gmail.com",
        "webToken": "10928312313.1209381031.123091823",
        "senacCredentials": {
          "username": "631420378",
          "unity": 63,
          "storePassword": false,
          "lastSync": "4/19/2017 22:32:03",
          "isSyncing": false
        }
      }
    },
    "Class": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string"
        },
        "ano": {
          "type": "integer"
        },
        "semestre": {
          "type": "integer"
        },
        "periodo": {
          "type": "string"
        },
        "descricaoDisciplina": {
          "type": "string"
        },
        "descricaoReduzidaDisciplina": {
          "type": "string"
        },
        "notas": {
          "type": "object",
          "properties": {
            "conceito": {
              "type": "string"
            },
            "parciais": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "descricao": {
                    "type": "string"
                  },
                  "descricaoReduzida": {
                    "type": "string"
                  },
                  "ordemParcial": {
                    "type": "integer"
                  },
                  "valorAvaliacaoParcial": {
                    "type": "integer"
                  }
                }
              }
            }
          }
        },
        "faltas": {
          "type": "object",
          "properties": {
            "total": {
              "type": "integer"
            }
          }
        }
      },
      "example": {
        "_id": "58f18e0275b5be4e92182854",
        "ano": 2016,
        "semestre": 1,
        "periodo": "2016|1",
        "descricaoDisciplina": "Sistemas Distribuídos",
        "descricaoReduzidaDisciplina": "SIST.DISTR",
        "notas": {
          "parciais": [
            {
              "descricao": "Trabalho 1",
              "descricaoReduzida": "T1",
              "ordemParcial": 1,
              "valorAvaliacaoParcial": "B"
            }
          ],
          "conceito": "B"
        },
        "faltas": {
          "total": 4
        }
      }
    }
  }
}
